name: Custom host tools
run-name: Build custom Linux host tools

on:
  workflow_dispatch:
  push:
    branches:
      - custom

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux-x64:
    name: Linux x64 GCC
    uses: ./.github/workflows/buildx.yml
    with:
      args: gcc
      suffix: custom-lnx-x64-gcc
      gitpath: rel
      owtools: GCC
      image: ubuntu-latest
      docbuild: ''
      run_tests: ''

  macos-arm64:
    name: macOS arm64 Clang
    uses: ./.github/workflows/buildx.yml
    with:
      args: clang
      suffix: custom-osx-a64-clang
      gitpath: rel
      owtools: CLANG
      image: macos-15
      docbuild: ''
      run_tests: ''
